version: '3.0'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tmpfs:
      - /tmp
      - /app/tmp/pids
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    environment:
      RAILS_ENV: development
      DB_HOST: postgres
      REDIS_URL: redis://redis:6379/0

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user_dev
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432
    healthcheck:
      test: pg_isready -U user_dev -h 127.0.0.1
      interval: 5s

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - 6379:6379

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - postgres
      - redis
    environment:
      RAILS_ENV: development
      DB_HOST: postgres
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/app

volumes:
  postgres_data:
