version: '3.0'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tmpfs:
      - /tmp
      - /app/tmp/pids
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -h 127.0.0.1
      interval: 5s

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - 6380:6379

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app

volumes:
  postgres_data:
