test:
  REDIS_URL: 'redis://localhost:6379'

  noreply_email: 'noreply@mailing.webgate.pro'
  support_email: 'support@webgate.pro'
  notify_email: 'notifier@webgate.pro'
  office_email: 'biuro@webgate.pro'

  smtp_data:
    address: localhost
    port: 1025
    domain: webgate.pro
