default: &default
  adapter: postgresql
  encoding: unicode
  host:     <%= Settings.db.host %>
  port:     <%= Settings.db.port %>
  database: <%= Settings.db.name %>
  pool:     <%= Settings.db.pool %>
  username: <%= Settings.db.user %>
  password: <%= Settings.db.pass %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
