default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: webgate_pro_development

test:
  <<: *default
  database: webgate_pro_test

production:
  <<: *default
  database: webgate_pro_production
